//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarForm.AracWebServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Araclar", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Araclar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AracIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlakaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracModeliField;
        
        private int GerekenEhliyetYasiField;
        
        private int MinimumYasSiniriField;
        
        private int GunlukKmSiniriField;
        
        private int AracKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HavaYastigiField;
        
        private int BagajHacmiField;
        
        private int KoltukSayisiField;
        
        private int GunlukKiraBedeliField;
        
        private bool RezervField;
        
        private bool KiradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YakitTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VitesTipiField;
        
        private System.DateTime KiralanmaTarihiField;
        
        private System.DateTime KiradanDonusTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracResmiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentACarForm.AracWebServis.Musteriler MusteriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AracId {
            get {
                return this.AracIdField;
            }
            set {
                if ((this.AracIdField.Equals(value) != true)) {
                    this.AracIdField = value;
                    this.RaisePropertyChanged("AracId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Plaka {
            get {
                return this.PlakaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlakaField, value) != true)) {
                    this.PlakaField = value;
                    this.RaisePropertyChanged("Plaka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AracAdi {
            get {
                return this.AracAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AracAdiField, value) != true)) {
                    this.AracAdiField = value;
                    this.RaisePropertyChanged("AracAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AracModeli {
            get {
                return this.AracModeliField;
            }
            set {
                if ((object.ReferenceEquals(this.AracModeliField, value) != true)) {
                    this.AracModeliField = value;
                    this.RaisePropertyChanged("AracModeli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int GerekenEhliyetYasi {
            get {
                return this.GerekenEhliyetYasiField;
            }
            set {
                if ((this.GerekenEhliyetYasiField.Equals(value) != true)) {
                    this.GerekenEhliyetYasiField = value;
                    this.RaisePropertyChanged("GerekenEhliyetYasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int MinimumYasSiniri {
            get {
                return this.MinimumYasSiniriField;
            }
            set {
                if ((this.MinimumYasSiniriField.Equals(value) != true)) {
                    this.MinimumYasSiniriField = value;
                    this.RaisePropertyChanged("MinimumYasSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int GunlukKmSiniri {
            get {
                return this.GunlukKmSiniriField;
            }
            set {
                if ((this.GunlukKmSiniriField.Equals(value) != true)) {
                    this.GunlukKmSiniriField = value;
                    this.RaisePropertyChanged("GunlukKmSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int AracKm {
            get {
                return this.AracKmField;
            }
            set {
                if ((this.AracKmField.Equals(value) != true)) {
                    this.AracKmField = value;
                    this.RaisePropertyChanged("AracKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string HavaYastigi {
            get {
                return this.HavaYastigiField;
            }
            set {
                if ((object.ReferenceEquals(this.HavaYastigiField, value) != true)) {
                    this.HavaYastigiField = value;
                    this.RaisePropertyChanged("HavaYastigi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int BagajHacmi {
            get {
                return this.BagajHacmiField;
            }
            set {
                if ((this.BagajHacmiField.Equals(value) != true)) {
                    this.BagajHacmiField = value;
                    this.RaisePropertyChanged("BagajHacmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int KoltukSayisi {
            get {
                return this.KoltukSayisiField;
            }
            set {
                if ((this.KoltukSayisiField.Equals(value) != true)) {
                    this.KoltukSayisiField = value;
                    this.RaisePropertyChanged("KoltukSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int GunlukKiraBedeli {
            get {
                return this.GunlukKiraBedeliField;
            }
            set {
                if ((this.GunlukKiraBedeliField.Equals(value) != true)) {
                    this.GunlukKiraBedeliField = value;
                    this.RaisePropertyChanged("GunlukKiraBedeli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool Rezerv {
            get {
                return this.RezervField;
            }
            set {
                if ((this.RezervField.Equals(value) != true)) {
                    this.RezervField = value;
                    this.RaisePropertyChanged("Rezerv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool Kirada {
            get {
                return this.KiradaField;
            }
            set {
                if ((this.KiradaField.Equals(value) != true)) {
                    this.KiradaField = value;
                    this.RaisePropertyChanged("Kirada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string YakitTipi {
            get {
                return this.YakitTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.YakitTipiField, value) != true)) {
                    this.YakitTipiField = value;
                    this.RaisePropertyChanged("YakitTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string VitesTipi {
            get {
                return this.VitesTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.VitesTipiField, value) != true)) {
                    this.VitesTipiField = value;
                    this.RaisePropertyChanged("VitesTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.DateTime KiralanmaTarihi {
            get {
                return this.KiralanmaTarihiField;
            }
            set {
                if ((this.KiralanmaTarihiField.Equals(value) != true)) {
                    this.KiralanmaTarihiField = value;
                    this.RaisePropertyChanged("KiralanmaTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.DateTime KiradanDonusTarihi {
            get {
                return this.KiradanDonusTarihiField;
            }
            set {
                if ((this.KiradanDonusTarihiField.Equals(value) != true)) {
                    this.KiradanDonusTarihiField = value;
                    this.RaisePropertyChanged("KiradanDonusTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string AracResmi {
            get {
                return this.AracResmiField;
            }
            set {
                if ((object.ReferenceEquals(this.AracResmiField, value) != true)) {
                    this.AracResmiField = value;
                    this.RaisePropertyChanged("AracResmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public RentACarForm.AracWebServis.Musteriler Musteri {
            get {
                return this.MusteriField;
            }
            set {
                if ((object.ReferenceEquals(this.MusteriField, value) != true)) {
                    this.MusteriField = value;
                    this.RaisePropertyChanged("Musteri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Musteriler", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Musteriler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TcKimlikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private System.DateTime DogumTarihiField;
        
        private int MusteriIdField;
        
        private bool KaraListeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentACarForm.AracWebServis.Araclar[] AraclarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciAdiField;
        
        private System.DateTime EhliyetYilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EhliyetTipiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TcKimlik {
            get {
                return this.TcKimlikField;
            }
            set {
                if ((object.ReferenceEquals(this.TcKimlikField, value) != true)) {
                    this.TcKimlikField = value;
                    this.RaisePropertyChanged("TcKimlik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime DogumTarihi {
            get {
                return this.DogumTarihiField;
            }
            set {
                if ((this.DogumTarihiField.Equals(value) != true)) {
                    this.DogumTarihiField = value;
                    this.RaisePropertyChanged("DogumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int MusteriId {
            get {
                return this.MusteriIdField;
            }
            set {
                if ((this.MusteriIdField.Equals(value) != true)) {
                    this.MusteriIdField = value;
                    this.RaisePropertyChanged("MusteriId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool KaraListe {
            get {
                return this.KaraListeField;
            }
            set {
                if ((this.KaraListeField.Equals(value) != true)) {
                    this.KaraListeField = value;
                    this.RaisePropertyChanged("KaraListe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public RentACarForm.AracWebServis.Araclar[] Araclar {
            get {
                return this.AraclarField;
            }
            set {
                if ((object.ReferenceEquals(this.AraclarField, value) != true)) {
                    this.AraclarField = value;
                    this.RaisePropertyChanged("Araclar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string KullaniciAdi {
            get {
                return this.KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciAdiField, value) != true)) {
                    this.KullaniciAdiField = value;
                    this.RaisePropertyChanged("KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.DateTime EhliyetYil {
            get {
                return this.EhliyetYilField;
            }
            set {
                if ((this.EhliyetYilField.Equals(value) != true)) {
                    this.EhliyetYilField = value;
                    this.RaisePropertyChanged("EhliyetYil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string EhliyetTipi {
            get {
                return this.EhliyetTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.EhliyetTipiField, value) != true)) {
                    this.EhliyetTipiField = value;
                    this.RaisePropertyChanged("EhliyetTipi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AracWebServis.AracWebServisSoap")]
    public interface AracWebServisSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracEkle", ReplyAction="*")]
        RentACarForm.AracWebServis.AracEkleResponse AracEkle(RentACarForm.AracWebServis.AracEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.AracWebServis.AracEkleResponse> AracEkleAsync(RentACarForm.AracWebServis.AracEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracKiralama", ReplyAction="*")]
        bool AracKiralama(int aracId, int musteriId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracKiralama", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AracKiralamaAsync(int aracId, int musteriId);
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracGuncelle", ReplyAction="*")]
        RentACarForm.AracWebServis.AracGuncelleResponse AracGuncelle(RentACarForm.AracWebServis.AracGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.AracWebServis.AracGuncelleResponse> AracGuncelleAsync(RentACarForm.AracWebServis.AracGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracIdSil", ReplyAction="*")]
        bool AracIdSil(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracIdSil", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AracIdSilAsync(int id);
        
        // CODEGEN: Generating message contract since element name AracHepsiniSecResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracHepsiniSec", ReplyAction="*")]
        RentACarForm.AracWebServis.AracHepsiniSecResponse AracHepsiniSec(RentACarForm.AracWebServis.AracHepsiniSecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracHepsiniSec", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.AracWebServis.AracHepsiniSecResponse> AracHepsiniSecAsync(RentACarForm.AracWebServis.AracHepsiniSecRequest request);
        
        // CODEGEN: Generating message contract since element name AracIdSecResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracIdSec", ReplyAction="*")]
        RentACarForm.AracWebServis.AracIdSecResponse AracIdSec(RentACarForm.AracWebServis.AracIdSecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracIdSec", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.AracWebServis.AracIdSecResponse> AracIdSecAsync(RentACarForm.AracWebServis.AracIdSecRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracEkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracEkle", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.AracWebServis.AracEkleRequestBody Body;
        
        public AracEkleRequest() {
        }
        
        public AracEkleRequest(RentACarForm.AracWebServis.AracEkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracEkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.AracWebServis.Araclar entity;
        
        public AracEkleRequestBody() {
        }
        
        public AracEkleRequestBody(RentACarForm.AracWebServis.Araclar entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracEkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracEkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.AracWebServis.AracEkleResponseBody Body;
        
        public AracEkleResponse() {
        }
        
        public AracEkleResponse(RentACarForm.AracWebServis.AracEkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracEkleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AracEkleResult;
        
        public AracEkleResponseBody() {
        }
        
        public AracEkleResponseBody(bool AracEkleResult) {
            this.AracEkleResult = AracEkleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracGuncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracGuncelle", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.AracWebServis.AracGuncelleRequestBody Body;
        
        public AracGuncelleRequest() {
        }
        
        public AracGuncelleRequest(RentACarForm.AracWebServis.AracGuncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracGuncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.AracWebServis.Araclar entity;
        
        public AracGuncelleRequestBody() {
        }
        
        public AracGuncelleRequestBody(RentACarForm.AracWebServis.Araclar entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracGuncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracGuncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.AracWebServis.AracGuncelleResponseBody Body;
        
        public AracGuncelleResponse() {
        }
        
        public AracGuncelleResponse(RentACarForm.AracWebServis.AracGuncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracGuncelleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AracGuncelleResult;
        
        public AracGuncelleResponseBody() {
        }
        
        public AracGuncelleResponseBody(bool AracGuncelleResult) {
            this.AracGuncelleResult = AracGuncelleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracHepsiniSecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracHepsiniSec", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.AracWebServis.AracHepsiniSecRequestBody Body;
        
        public AracHepsiniSecRequest() {
        }
        
        public AracHepsiniSecRequest(RentACarForm.AracWebServis.AracHepsiniSecRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AracHepsiniSecRequestBody {
        
        public AracHepsiniSecRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracHepsiniSecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracHepsiniSecResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.AracWebServis.AracHepsiniSecResponseBody Body;
        
        public AracHepsiniSecResponse() {
        }
        
        public AracHepsiniSecResponse(RentACarForm.AracWebServis.AracHepsiniSecResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracHepsiniSecResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.AracWebServis.Araclar[] AracHepsiniSecResult;
        
        public AracHepsiniSecResponseBody() {
        }
        
        public AracHepsiniSecResponseBody(RentACarForm.AracWebServis.Araclar[] AracHepsiniSecResult) {
            this.AracHepsiniSecResult = AracHepsiniSecResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracIdSecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracIdSec", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.AracWebServis.AracIdSecRequestBody Body;
        
        public AracIdSecRequest() {
        }
        
        public AracIdSecRequest(RentACarForm.AracWebServis.AracIdSecRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracIdSecRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public AracIdSecRequestBody() {
        }
        
        public AracIdSecRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracIdSecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracIdSecResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.AracWebServis.AracIdSecResponseBody Body;
        
        public AracIdSecResponse() {
        }
        
        public AracIdSecResponse(RentACarForm.AracWebServis.AracIdSecResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracIdSecResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.AracWebServis.Araclar AracIdSecResult;
        
        public AracIdSecResponseBody() {
        }
        
        public AracIdSecResponseBody(RentACarForm.AracWebServis.Araclar AracIdSecResult) {
            this.AracIdSecResult = AracIdSecResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AracWebServisSoapChannel : RentACarForm.AracWebServis.AracWebServisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AracWebServisSoapClient : System.ServiceModel.ClientBase<RentACarForm.AracWebServis.AracWebServisSoap>, RentACarForm.AracWebServis.AracWebServisSoap {
        
        public AracWebServisSoapClient() {
        }
        
        public AracWebServisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AracWebServisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracWebServisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracWebServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.AracWebServis.AracEkleResponse RentACarForm.AracWebServis.AracWebServisSoap.AracEkle(RentACarForm.AracWebServis.AracEkleRequest request) {
            return base.Channel.AracEkle(request);
        }
        
        public bool AracEkle(RentACarForm.AracWebServis.Araclar entity) {
            RentACarForm.AracWebServis.AracEkleRequest inValue = new RentACarForm.AracWebServis.AracEkleRequest();
            inValue.Body = new RentACarForm.AracWebServis.AracEkleRequestBody();
            inValue.Body.entity = entity;
            RentACarForm.AracWebServis.AracEkleResponse retVal = ((RentACarForm.AracWebServis.AracWebServisSoap)(this)).AracEkle(inValue);
            return retVal.Body.AracEkleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.AracWebServis.AracEkleResponse> RentACarForm.AracWebServis.AracWebServisSoap.AracEkleAsync(RentACarForm.AracWebServis.AracEkleRequest request) {
            return base.Channel.AracEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.AracWebServis.AracEkleResponse> AracEkleAsync(RentACarForm.AracWebServis.Araclar entity) {
            RentACarForm.AracWebServis.AracEkleRequest inValue = new RentACarForm.AracWebServis.AracEkleRequest();
            inValue.Body = new RentACarForm.AracWebServis.AracEkleRequestBody();
            inValue.Body.entity = entity;
            return ((RentACarForm.AracWebServis.AracWebServisSoap)(this)).AracEkleAsync(inValue);
        }
        
        public bool AracKiralama(int aracId, int musteriId) {
            return base.Channel.AracKiralama(aracId, musteriId);
        }
        
        public System.Threading.Tasks.Task<bool> AracKiralamaAsync(int aracId, int musteriId) {
            return base.Channel.AracKiralamaAsync(aracId, musteriId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.AracWebServis.AracGuncelleResponse RentACarForm.AracWebServis.AracWebServisSoap.AracGuncelle(RentACarForm.AracWebServis.AracGuncelleRequest request) {
            return base.Channel.AracGuncelle(request);
        }
        
        public bool AracGuncelle(RentACarForm.AracWebServis.Araclar entity) {
            RentACarForm.AracWebServis.AracGuncelleRequest inValue = new RentACarForm.AracWebServis.AracGuncelleRequest();
            inValue.Body = new RentACarForm.AracWebServis.AracGuncelleRequestBody();
            inValue.Body.entity = entity;
            RentACarForm.AracWebServis.AracGuncelleResponse retVal = ((RentACarForm.AracWebServis.AracWebServisSoap)(this)).AracGuncelle(inValue);
            return retVal.Body.AracGuncelleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.AracWebServis.AracGuncelleResponse> RentACarForm.AracWebServis.AracWebServisSoap.AracGuncelleAsync(RentACarForm.AracWebServis.AracGuncelleRequest request) {
            return base.Channel.AracGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.AracWebServis.AracGuncelleResponse> AracGuncelleAsync(RentACarForm.AracWebServis.Araclar entity) {
            RentACarForm.AracWebServis.AracGuncelleRequest inValue = new RentACarForm.AracWebServis.AracGuncelleRequest();
            inValue.Body = new RentACarForm.AracWebServis.AracGuncelleRequestBody();
            inValue.Body.entity = entity;
            return ((RentACarForm.AracWebServis.AracWebServisSoap)(this)).AracGuncelleAsync(inValue);
        }
        
        public bool AracIdSil(int id) {
            return base.Channel.AracIdSil(id);
        }
        
        public System.Threading.Tasks.Task<bool> AracIdSilAsync(int id) {
            return base.Channel.AracIdSilAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.AracWebServis.AracHepsiniSecResponse RentACarForm.AracWebServis.AracWebServisSoap.AracHepsiniSec(RentACarForm.AracWebServis.AracHepsiniSecRequest request) {
            return base.Channel.AracHepsiniSec(request);
        }
        
        public RentACarForm.AracWebServis.Araclar[] AracHepsiniSec() {
            RentACarForm.AracWebServis.AracHepsiniSecRequest inValue = new RentACarForm.AracWebServis.AracHepsiniSecRequest();
            inValue.Body = new RentACarForm.AracWebServis.AracHepsiniSecRequestBody();
            RentACarForm.AracWebServis.AracHepsiniSecResponse retVal = ((RentACarForm.AracWebServis.AracWebServisSoap)(this)).AracHepsiniSec(inValue);
            return retVal.Body.AracHepsiniSecResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.AracWebServis.AracHepsiniSecResponse> RentACarForm.AracWebServis.AracWebServisSoap.AracHepsiniSecAsync(RentACarForm.AracWebServis.AracHepsiniSecRequest request) {
            return base.Channel.AracHepsiniSecAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.AracWebServis.AracHepsiniSecResponse> AracHepsiniSecAsync() {
            RentACarForm.AracWebServis.AracHepsiniSecRequest inValue = new RentACarForm.AracWebServis.AracHepsiniSecRequest();
            inValue.Body = new RentACarForm.AracWebServis.AracHepsiniSecRequestBody();
            return ((RentACarForm.AracWebServis.AracWebServisSoap)(this)).AracHepsiniSecAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.AracWebServis.AracIdSecResponse RentACarForm.AracWebServis.AracWebServisSoap.AracIdSec(RentACarForm.AracWebServis.AracIdSecRequest request) {
            return base.Channel.AracIdSec(request);
        }
        
        public RentACarForm.AracWebServis.Araclar AracIdSec(int id) {
            RentACarForm.AracWebServis.AracIdSecRequest inValue = new RentACarForm.AracWebServis.AracIdSecRequest();
            inValue.Body = new RentACarForm.AracWebServis.AracIdSecRequestBody();
            inValue.Body.id = id;
            RentACarForm.AracWebServis.AracIdSecResponse retVal = ((RentACarForm.AracWebServis.AracWebServisSoap)(this)).AracIdSec(inValue);
            return retVal.Body.AracIdSecResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.AracWebServis.AracIdSecResponse> RentACarForm.AracWebServis.AracWebServisSoap.AracIdSecAsync(RentACarForm.AracWebServis.AracIdSecRequest request) {
            return base.Channel.AracIdSecAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.AracWebServis.AracIdSecResponse> AracIdSecAsync(int id) {
            RentACarForm.AracWebServis.AracIdSecRequest inValue = new RentACarForm.AracWebServis.AracIdSecRequest();
            inValue.Body = new RentACarForm.AracWebServis.AracIdSecRequestBody();
            inValue.Body.id = id;
            return ((RentACarForm.AracWebServis.AracWebServisSoap)(this)).AracIdSecAsync(inValue);
        }
    }
}
