//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarForm.YoneticiWebServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Yonetici", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Yonetici : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TcKimlikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private System.DateTime DogumTarihiField;
        
        private int YoneticiIdField;
        
        private int SirketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TcKimlik {
            get {
                return this.TcKimlikField;
            }
            set {
                if ((object.ReferenceEquals(this.TcKimlikField, value) != true)) {
                    this.TcKimlikField = value;
                    this.RaisePropertyChanged("TcKimlik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime DogumTarihi {
            get {
                return this.DogumTarihiField;
            }
            set {
                if ((this.DogumTarihiField.Equals(value) != true)) {
                    this.DogumTarihiField = value;
                    this.RaisePropertyChanged("DogumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int YoneticiId {
            get {
                return this.YoneticiIdField;
            }
            set {
                if ((this.YoneticiIdField.Equals(value) != true)) {
                    this.YoneticiIdField = value;
                    this.RaisePropertyChanged("YoneticiId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int SirketId {
            get {
                return this.SirketIdField;
            }
            set {
                if ((this.SirketIdField.Equals(value) != true)) {
                    this.SirketIdField = value;
                    this.RaisePropertyChanged("SirketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="YoneticiWebServis.YoneticiWebServisSoap")]
    public interface YoneticiWebServisSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YoneticiEkle", ReplyAction="*")]
        RentACarForm.YoneticiWebServis.YoneticiEkleResponse YoneticiEkle(RentACarForm.YoneticiWebServis.YoneticiEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YoneticiEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.YoneticiWebServis.YoneticiEkleResponse> YoneticiEkleAsync(RentACarForm.YoneticiWebServis.YoneticiEkleRequest request);
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YoneticiGuncelle", ReplyAction="*")]
        RentACarForm.YoneticiWebServis.YoneticiGuncelleResponse YoneticiGuncelle(RentACarForm.YoneticiWebServis.YoneticiGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YoneticiGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.YoneticiWebServis.YoneticiGuncelleResponse> YoneticiGuncelleAsync(RentACarForm.YoneticiWebServis.YoneticiGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YoneticiIdSil", ReplyAction="*")]
        bool YoneticiIdSil(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YoneticiIdSil", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> YoneticiIdSilAsync(int id);
        
        // CODEGEN: Generating message contract since element name YoneticiHepsiniSecResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YoneticiHepsiniSec", ReplyAction="*")]
        RentACarForm.YoneticiWebServis.YoneticiHepsiniSecResponse YoneticiHepsiniSec(RentACarForm.YoneticiWebServis.YoneticiHepsiniSecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YoneticiHepsiniSec", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.YoneticiWebServis.YoneticiHepsiniSecResponse> YoneticiHepsiniSecAsync(RentACarForm.YoneticiWebServis.YoneticiHepsiniSecRequest request);
        
        // CODEGEN: Generating message contract since element name YoneticiIdSecResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YoneticiIdSec", ReplyAction="*")]
        RentACarForm.YoneticiWebServis.YoneticiIdSecResponse YoneticiIdSec(RentACarForm.YoneticiWebServis.YoneticiIdSecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YoneticiIdSec", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.YoneticiWebServis.YoneticiIdSecResponse> YoneticiIdSecAsync(RentACarForm.YoneticiWebServis.YoneticiIdSecRequest request);
        
        // CODEGEN: Generating message contract since element name TcKimlik from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GirisYap", ReplyAction="*")]
        RentACarForm.YoneticiWebServis.GirisYapResponse GirisYap(RentACarForm.YoneticiWebServis.GirisYapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GirisYap", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.YoneticiWebServis.GirisYapResponse> GirisYapAsync(RentACarForm.YoneticiWebServis.GirisYapRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YoneticiEkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YoneticiEkle", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.YoneticiWebServis.YoneticiEkleRequestBody Body;
        
        public YoneticiEkleRequest() {
        }
        
        public YoneticiEkleRequest(RentACarForm.YoneticiWebServis.YoneticiEkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class YoneticiEkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.YoneticiWebServis.Yonetici entity;
        
        public YoneticiEkleRequestBody() {
        }
        
        public YoneticiEkleRequestBody(RentACarForm.YoneticiWebServis.Yonetici entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YoneticiEkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YoneticiEkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.YoneticiWebServis.YoneticiEkleResponseBody Body;
        
        public YoneticiEkleResponse() {
        }
        
        public YoneticiEkleResponse(RentACarForm.YoneticiWebServis.YoneticiEkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class YoneticiEkleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool YoneticiEkleResult;
        
        public YoneticiEkleResponseBody() {
        }
        
        public YoneticiEkleResponseBody(bool YoneticiEkleResult) {
            this.YoneticiEkleResult = YoneticiEkleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YoneticiGuncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YoneticiGuncelle", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.YoneticiWebServis.YoneticiGuncelleRequestBody Body;
        
        public YoneticiGuncelleRequest() {
        }
        
        public YoneticiGuncelleRequest(RentACarForm.YoneticiWebServis.YoneticiGuncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class YoneticiGuncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.YoneticiWebServis.Yonetici entity;
        
        public YoneticiGuncelleRequestBody() {
        }
        
        public YoneticiGuncelleRequestBody(RentACarForm.YoneticiWebServis.Yonetici entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YoneticiGuncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YoneticiGuncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.YoneticiWebServis.YoneticiGuncelleResponseBody Body;
        
        public YoneticiGuncelleResponse() {
        }
        
        public YoneticiGuncelleResponse(RentACarForm.YoneticiWebServis.YoneticiGuncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class YoneticiGuncelleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool YoneticiGuncelleResult;
        
        public YoneticiGuncelleResponseBody() {
        }
        
        public YoneticiGuncelleResponseBody(bool YoneticiGuncelleResult) {
            this.YoneticiGuncelleResult = YoneticiGuncelleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YoneticiHepsiniSecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YoneticiHepsiniSec", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.YoneticiWebServis.YoneticiHepsiniSecRequestBody Body;
        
        public YoneticiHepsiniSecRequest() {
        }
        
        public YoneticiHepsiniSecRequest(RentACarForm.YoneticiWebServis.YoneticiHepsiniSecRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class YoneticiHepsiniSecRequestBody {
        
        public YoneticiHepsiniSecRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YoneticiHepsiniSecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YoneticiHepsiniSecResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.YoneticiWebServis.YoneticiHepsiniSecResponseBody Body;
        
        public YoneticiHepsiniSecResponse() {
        }
        
        public YoneticiHepsiniSecResponse(RentACarForm.YoneticiWebServis.YoneticiHepsiniSecResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class YoneticiHepsiniSecResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.YoneticiWebServis.Yonetici[] YoneticiHepsiniSecResult;
        
        public YoneticiHepsiniSecResponseBody() {
        }
        
        public YoneticiHepsiniSecResponseBody(RentACarForm.YoneticiWebServis.Yonetici[] YoneticiHepsiniSecResult) {
            this.YoneticiHepsiniSecResult = YoneticiHepsiniSecResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YoneticiIdSecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YoneticiIdSec", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.YoneticiWebServis.YoneticiIdSecRequestBody Body;
        
        public YoneticiIdSecRequest() {
        }
        
        public YoneticiIdSecRequest(RentACarForm.YoneticiWebServis.YoneticiIdSecRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class YoneticiIdSecRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public YoneticiIdSecRequestBody() {
        }
        
        public YoneticiIdSecRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YoneticiIdSecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YoneticiIdSecResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.YoneticiWebServis.YoneticiIdSecResponseBody Body;
        
        public YoneticiIdSecResponse() {
        }
        
        public YoneticiIdSecResponse(RentACarForm.YoneticiWebServis.YoneticiIdSecResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class YoneticiIdSecResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.YoneticiWebServis.Yonetici YoneticiIdSecResult;
        
        public YoneticiIdSecResponseBody() {
        }
        
        public YoneticiIdSecResponseBody(RentACarForm.YoneticiWebServis.Yonetici YoneticiIdSecResult) {
            this.YoneticiIdSecResult = YoneticiIdSecResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GirisYapRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GirisYap", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.YoneticiWebServis.GirisYapRequestBody Body;
        
        public GirisYapRequest() {
        }
        
        public GirisYapRequest(RentACarForm.YoneticiWebServis.GirisYapRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GirisYapRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TcKimlik;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Sifre;
        
        public GirisYapRequestBody() {
        }
        
        public GirisYapRequestBody(string TcKimlik, string Sifre) {
            this.TcKimlik = TcKimlik;
            this.Sifre = Sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GirisYapResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GirisYapResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.YoneticiWebServis.GirisYapResponseBody Body;
        
        public GirisYapResponse() {
        }
        
        public GirisYapResponse(RentACarForm.YoneticiWebServis.GirisYapResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GirisYapResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GirisYapResult;
        
        public GirisYapResponseBody() {
        }
        
        public GirisYapResponseBody(bool GirisYapResult) {
            this.GirisYapResult = GirisYapResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface YoneticiWebServisSoapChannel : RentACarForm.YoneticiWebServis.YoneticiWebServisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class YoneticiWebServisSoapClient : System.ServiceModel.ClientBase<RentACarForm.YoneticiWebServis.YoneticiWebServisSoap>, RentACarForm.YoneticiWebServis.YoneticiWebServisSoap {
        
        public YoneticiWebServisSoapClient() {
        }
        
        public YoneticiWebServisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public YoneticiWebServisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YoneticiWebServisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YoneticiWebServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.YoneticiWebServis.YoneticiEkleResponse RentACarForm.YoneticiWebServis.YoneticiWebServisSoap.YoneticiEkle(RentACarForm.YoneticiWebServis.YoneticiEkleRequest request) {
            return base.Channel.YoneticiEkle(request);
        }
        
        public bool YoneticiEkle(RentACarForm.YoneticiWebServis.Yonetici entity) {
            RentACarForm.YoneticiWebServis.YoneticiEkleRequest inValue = new RentACarForm.YoneticiWebServis.YoneticiEkleRequest();
            inValue.Body = new RentACarForm.YoneticiWebServis.YoneticiEkleRequestBody();
            inValue.Body.entity = entity;
            RentACarForm.YoneticiWebServis.YoneticiEkleResponse retVal = ((RentACarForm.YoneticiWebServis.YoneticiWebServisSoap)(this)).YoneticiEkle(inValue);
            return retVal.Body.YoneticiEkleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.YoneticiWebServis.YoneticiEkleResponse> RentACarForm.YoneticiWebServis.YoneticiWebServisSoap.YoneticiEkleAsync(RentACarForm.YoneticiWebServis.YoneticiEkleRequest request) {
            return base.Channel.YoneticiEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.YoneticiWebServis.YoneticiEkleResponse> YoneticiEkleAsync(RentACarForm.YoneticiWebServis.Yonetici entity) {
            RentACarForm.YoneticiWebServis.YoneticiEkleRequest inValue = new RentACarForm.YoneticiWebServis.YoneticiEkleRequest();
            inValue.Body = new RentACarForm.YoneticiWebServis.YoneticiEkleRequestBody();
            inValue.Body.entity = entity;
            return ((RentACarForm.YoneticiWebServis.YoneticiWebServisSoap)(this)).YoneticiEkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.YoneticiWebServis.YoneticiGuncelleResponse RentACarForm.YoneticiWebServis.YoneticiWebServisSoap.YoneticiGuncelle(RentACarForm.YoneticiWebServis.YoneticiGuncelleRequest request) {
            return base.Channel.YoneticiGuncelle(request);
        }
        
        public bool YoneticiGuncelle(RentACarForm.YoneticiWebServis.Yonetici entity) {
            RentACarForm.YoneticiWebServis.YoneticiGuncelleRequest inValue = new RentACarForm.YoneticiWebServis.YoneticiGuncelleRequest();
            inValue.Body = new RentACarForm.YoneticiWebServis.YoneticiGuncelleRequestBody();
            inValue.Body.entity = entity;
            RentACarForm.YoneticiWebServis.YoneticiGuncelleResponse retVal = ((RentACarForm.YoneticiWebServis.YoneticiWebServisSoap)(this)).YoneticiGuncelle(inValue);
            return retVal.Body.YoneticiGuncelleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.YoneticiWebServis.YoneticiGuncelleResponse> RentACarForm.YoneticiWebServis.YoneticiWebServisSoap.YoneticiGuncelleAsync(RentACarForm.YoneticiWebServis.YoneticiGuncelleRequest request) {
            return base.Channel.YoneticiGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.YoneticiWebServis.YoneticiGuncelleResponse> YoneticiGuncelleAsync(RentACarForm.YoneticiWebServis.Yonetici entity) {
            RentACarForm.YoneticiWebServis.YoneticiGuncelleRequest inValue = new RentACarForm.YoneticiWebServis.YoneticiGuncelleRequest();
            inValue.Body = new RentACarForm.YoneticiWebServis.YoneticiGuncelleRequestBody();
            inValue.Body.entity = entity;
            return ((RentACarForm.YoneticiWebServis.YoneticiWebServisSoap)(this)).YoneticiGuncelleAsync(inValue);
        }
        
        public bool YoneticiIdSil(int id) {
            return base.Channel.YoneticiIdSil(id);
        }
        
        public System.Threading.Tasks.Task<bool> YoneticiIdSilAsync(int id) {
            return base.Channel.YoneticiIdSilAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.YoneticiWebServis.YoneticiHepsiniSecResponse RentACarForm.YoneticiWebServis.YoneticiWebServisSoap.YoneticiHepsiniSec(RentACarForm.YoneticiWebServis.YoneticiHepsiniSecRequest request) {
            return base.Channel.YoneticiHepsiniSec(request);
        }
        
        public RentACarForm.YoneticiWebServis.Yonetici[] YoneticiHepsiniSec() {
            RentACarForm.YoneticiWebServis.YoneticiHepsiniSecRequest inValue = new RentACarForm.YoneticiWebServis.YoneticiHepsiniSecRequest();
            inValue.Body = new RentACarForm.YoneticiWebServis.YoneticiHepsiniSecRequestBody();
            RentACarForm.YoneticiWebServis.YoneticiHepsiniSecResponse retVal = ((RentACarForm.YoneticiWebServis.YoneticiWebServisSoap)(this)).YoneticiHepsiniSec(inValue);
            return retVal.Body.YoneticiHepsiniSecResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.YoneticiWebServis.YoneticiHepsiniSecResponse> RentACarForm.YoneticiWebServis.YoneticiWebServisSoap.YoneticiHepsiniSecAsync(RentACarForm.YoneticiWebServis.YoneticiHepsiniSecRequest request) {
            return base.Channel.YoneticiHepsiniSecAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.YoneticiWebServis.YoneticiHepsiniSecResponse> YoneticiHepsiniSecAsync() {
            RentACarForm.YoneticiWebServis.YoneticiHepsiniSecRequest inValue = new RentACarForm.YoneticiWebServis.YoneticiHepsiniSecRequest();
            inValue.Body = new RentACarForm.YoneticiWebServis.YoneticiHepsiniSecRequestBody();
            return ((RentACarForm.YoneticiWebServis.YoneticiWebServisSoap)(this)).YoneticiHepsiniSecAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.YoneticiWebServis.YoneticiIdSecResponse RentACarForm.YoneticiWebServis.YoneticiWebServisSoap.YoneticiIdSec(RentACarForm.YoneticiWebServis.YoneticiIdSecRequest request) {
            return base.Channel.YoneticiIdSec(request);
        }
        
        public RentACarForm.YoneticiWebServis.Yonetici YoneticiIdSec(int id) {
            RentACarForm.YoneticiWebServis.YoneticiIdSecRequest inValue = new RentACarForm.YoneticiWebServis.YoneticiIdSecRequest();
            inValue.Body = new RentACarForm.YoneticiWebServis.YoneticiIdSecRequestBody();
            inValue.Body.id = id;
            RentACarForm.YoneticiWebServis.YoneticiIdSecResponse retVal = ((RentACarForm.YoneticiWebServis.YoneticiWebServisSoap)(this)).YoneticiIdSec(inValue);
            return retVal.Body.YoneticiIdSecResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.YoneticiWebServis.YoneticiIdSecResponse> RentACarForm.YoneticiWebServis.YoneticiWebServisSoap.YoneticiIdSecAsync(RentACarForm.YoneticiWebServis.YoneticiIdSecRequest request) {
            return base.Channel.YoneticiIdSecAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.YoneticiWebServis.YoneticiIdSecResponse> YoneticiIdSecAsync(int id) {
            RentACarForm.YoneticiWebServis.YoneticiIdSecRequest inValue = new RentACarForm.YoneticiWebServis.YoneticiIdSecRequest();
            inValue.Body = new RentACarForm.YoneticiWebServis.YoneticiIdSecRequestBody();
            inValue.Body.id = id;
            return ((RentACarForm.YoneticiWebServis.YoneticiWebServisSoap)(this)).YoneticiIdSecAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.YoneticiWebServis.GirisYapResponse RentACarForm.YoneticiWebServis.YoneticiWebServisSoap.GirisYap(RentACarForm.YoneticiWebServis.GirisYapRequest request) {
            return base.Channel.GirisYap(request);
        }
        
        public bool GirisYap(string TcKimlik, string Sifre) {
            RentACarForm.YoneticiWebServis.GirisYapRequest inValue = new RentACarForm.YoneticiWebServis.GirisYapRequest();
            inValue.Body = new RentACarForm.YoneticiWebServis.GirisYapRequestBody();
            inValue.Body.TcKimlik = TcKimlik;
            inValue.Body.Sifre = Sifre;
            RentACarForm.YoneticiWebServis.GirisYapResponse retVal = ((RentACarForm.YoneticiWebServis.YoneticiWebServisSoap)(this)).GirisYap(inValue);
            return retVal.Body.GirisYapResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.YoneticiWebServis.GirisYapResponse> RentACarForm.YoneticiWebServis.YoneticiWebServisSoap.GirisYapAsync(RentACarForm.YoneticiWebServis.GirisYapRequest request) {
            return base.Channel.GirisYapAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.YoneticiWebServis.GirisYapResponse> GirisYapAsync(string TcKimlik, string Sifre) {
            RentACarForm.YoneticiWebServis.GirisYapRequest inValue = new RentACarForm.YoneticiWebServis.GirisYapRequest();
            inValue.Body = new RentACarForm.YoneticiWebServis.GirisYapRequestBody();
            inValue.Body.TcKimlik = TcKimlik;
            inValue.Body.Sifre = Sifre;
            return ((RentACarForm.YoneticiWebServis.YoneticiWebServisSoap)(this)).GirisYapAsync(inValue);
        }
    }
}
