//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarForm.OdemelerWebServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Odemeler", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Odemeler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentACarForm.OdemelerWebServis.Musteriler MusteriField;
        
        private int OdemeIDField;
        
        private decimal OdemeMiktariField;
        
        private bool OdemeBasariliField;
        
        private System.DateTime OdemeTarihiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public RentACarForm.OdemelerWebServis.Musteriler Musteri {
            get {
                return this.MusteriField;
            }
            set {
                if ((object.ReferenceEquals(this.MusteriField, value) != true)) {
                    this.MusteriField = value;
                    this.RaisePropertyChanged("Musteri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OdemeID {
            get {
                return this.OdemeIDField;
            }
            set {
                if ((this.OdemeIDField.Equals(value) != true)) {
                    this.OdemeIDField = value;
                    this.RaisePropertyChanged("OdemeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal OdemeMiktari {
            get {
                return this.OdemeMiktariField;
            }
            set {
                if ((this.OdemeMiktariField.Equals(value) != true)) {
                    this.OdemeMiktariField = value;
                    this.RaisePropertyChanged("OdemeMiktari");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool OdemeBasarili {
            get {
                return this.OdemeBasariliField;
            }
            set {
                if ((this.OdemeBasariliField.Equals(value) != true)) {
                    this.OdemeBasariliField = value;
                    this.RaisePropertyChanged("OdemeBasarili");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime OdemeTarihi {
            get {
                return this.OdemeTarihiField;
            }
            set {
                if ((this.OdemeTarihiField.Equals(value) != true)) {
                    this.OdemeTarihiField = value;
                    this.RaisePropertyChanged("OdemeTarihi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Musteriler", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Musteriler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MusteriIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TcKimlikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        private System.DateTime DogumTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EhliyetTipiField;
        
        private System.DateTime EhliyetYilField;
        
        private bool KaraListeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentACarForm.OdemelerWebServis.Araclar[] AraclarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MusteriId {
            get {
                return this.MusteriIdField;
            }
            set {
                if ((this.MusteriIdField.Equals(value) != true)) {
                    this.MusteriIdField = value;
                    this.RaisePropertyChanged("MusteriId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TcKimlik {
            get {
                return this.TcKimlikField;
            }
            set {
                if ((object.ReferenceEquals(this.TcKimlikField, value) != true)) {
                    this.TcKimlikField = value;
                    this.RaisePropertyChanged("TcKimlik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime DogumTarihi {
            get {
                return this.DogumTarihiField;
            }
            set {
                if ((this.DogumTarihiField.Equals(value) != true)) {
                    this.DogumTarihiField = value;
                    this.RaisePropertyChanged("DogumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string KullaniciAdi {
            get {
                return this.KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciAdiField, value) != true)) {
                    this.KullaniciAdiField = value;
                    this.RaisePropertyChanged("KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string EhliyetTipi {
            get {
                return this.EhliyetTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.EhliyetTipiField, value) != true)) {
                    this.EhliyetTipiField = value;
                    this.RaisePropertyChanged("EhliyetTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime EhliyetYil {
            get {
                return this.EhliyetYilField;
            }
            set {
                if ((this.EhliyetYilField.Equals(value) != true)) {
                    this.EhliyetYilField = value;
                    this.RaisePropertyChanged("EhliyetYil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool KaraListe {
            get {
                return this.KaraListeField;
            }
            set {
                if ((this.KaraListeField.Equals(value) != true)) {
                    this.KaraListeField = value;
                    this.RaisePropertyChanged("KaraListe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public RentACarForm.OdemelerWebServis.Araclar[] Araclar {
            get {
                return this.AraclarField;
            }
            set {
                if ((object.ReferenceEquals(this.AraclarField, value) != true)) {
                    this.AraclarField = value;
                    this.RaisePropertyChanged("Araclar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Araclar", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Araclar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AracIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlakaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracModeliField;
        
        private int GerekenEhliyetYasiField;
        
        private int MinimumYasSiniriField;
        
        private int GunlukKmSiniriField;
        
        private int AracKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HavaYastigiField;
        
        private int BagajHacmiField;
        
        private int KoltukSayisiField;
        
        private int GunlukKiraBedeliField;
        
        private bool RezervField;
        
        private bool KiradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YakitTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VitesTipiField;
        
        private System.DateTime KiralanmaTarihiField;
        
        private System.DateTime KiradanDonusTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracResmiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentACarForm.OdemelerWebServis.Musteriler MusteriField;
        
        private int SirketIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AracId {
            get {
                return this.AracIdField;
            }
            set {
                if ((this.AracIdField.Equals(value) != true)) {
                    this.AracIdField = value;
                    this.RaisePropertyChanged("AracId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Plaka {
            get {
                return this.PlakaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlakaField, value) != true)) {
                    this.PlakaField = value;
                    this.RaisePropertyChanged("Plaka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AracAdi {
            get {
                return this.AracAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AracAdiField, value) != true)) {
                    this.AracAdiField = value;
                    this.RaisePropertyChanged("AracAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AracModeli {
            get {
                return this.AracModeliField;
            }
            set {
                if ((object.ReferenceEquals(this.AracModeliField, value) != true)) {
                    this.AracModeliField = value;
                    this.RaisePropertyChanged("AracModeli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int GerekenEhliyetYasi {
            get {
                return this.GerekenEhliyetYasiField;
            }
            set {
                if ((this.GerekenEhliyetYasiField.Equals(value) != true)) {
                    this.GerekenEhliyetYasiField = value;
                    this.RaisePropertyChanged("GerekenEhliyetYasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int MinimumYasSiniri {
            get {
                return this.MinimumYasSiniriField;
            }
            set {
                if ((this.MinimumYasSiniriField.Equals(value) != true)) {
                    this.MinimumYasSiniriField = value;
                    this.RaisePropertyChanged("MinimumYasSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int GunlukKmSiniri {
            get {
                return this.GunlukKmSiniriField;
            }
            set {
                if ((this.GunlukKmSiniriField.Equals(value) != true)) {
                    this.GunlukKmSiniriField = value;
                    this.RaisePropertyChanged("GunlukKmSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int AracKm {
            get {
                return this.AracKmField;
            }
            set {
                if ((this.AracKmField.Equals(value) != true)) {
                    this.AracKmField = value;
                    this.RaisePropertyChanged("AracKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string HavaYastigi {
            get {
                return this.HavaYastigiField;
            }
            set {
                if ((object.ReferenceEquals(this.HavaYastigiField, value) != true)) {
                    this.HavaYastigiField = value;
                    this.RaisePropertyChanged("HavaYastigi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int BagajHacmi {
            get {
                return this.BagajHacmiField;
            }
            set {
                if ((this.BagajHacmiField.Equals(value) != true)) {
                    this.BagajHacmiField = value;
                    this.RaisePropertyChanged("BagajHacmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int KoltukSayisi {
            get {
                return this.KoltukSayisiField;
            }
            set {
                if ((this.KoltukSayisiField.Equals(value) != true)) {
                    this.KoltukSayisiField = value;
                    this.RaisePropertyChanged("KoltukSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int GunlukKiraBedeli {
            get {
                return this.GunlukKiraBedeliField;
            }
            set {
                if ((this.GunlukKiraBedeliField.Equals(value) != true)) {
                    this.GunlukKiraBedeliField = value;
                    this.RaisePropertyChanged("GunlukKiraBedeli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool Rezerv {
            get {
                return this.RezervField;
            }
            set {
                if ((this.RezervField.Equals(value) != true)) {
                    this.RezervField = value;
                    this.RaisePropertyChanged("Rezerv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool Kirada {
            get {
                return this.KiradaField;
            }
            set {
                if ((this.KiradaField.Equals(value) != true)) {
                    this.KiradaField = value;
                    this.RaisePropertyChanged("Kirada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string YakitTipi {
            get {
                return this.YakitTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.YakitTipiField, value) != true)) {
                    this.YakitTipiField = value;
                    this.RaisePropertyChanged("YakitTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string VitesTipi {
            get {
                return this.VitesTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.VitesTipiField, value) != true)) {
                    this.VitesTipiField = value;
                    this.RaisePropertyChanged("VitesTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.DateTime KiralanmaTarihi {
            get {
                return this.KiralanmaTarihiField;
            }
            set {
                if ((this.KiralanmaTarihiField.Equals(value) != true)) {
                    this.KiralanmaTarihiField = value;
                    this.RaisePropertyChanged("KiralanmaTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.DateTime KiradanDonusTarihi {
            get {
                return this.KiradanDonusTarihiField;
            }
            set {
                if ((this.KiradanDonusTarihiField.Equals(value) != true)) {
                    this.KiradanDonusTarihiField = value;
                    this.RaisePropertyChanged("KiradanDonusTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string AracResmi {
            get {
                return this.AracResmiField;
            }
            set {
                if ((object.ReferenceEquals(this.AracResmiField, value) != true)) {
                    this.AracResmiField = value;
                    this.RaisePropertyChanged("AracResmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public RentACarForm.OdemelerWebServis.Musteriler Musteri {
            get {
                return this.MusteriField;
            }
            set {
                if ((object.ReferenceEquals(this.MusteriField, value) != true)) {
                    this.MusteriField = value;
                    this.RaisePropertyChanged("Musteri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public int SirketId {
            get {
                return this.SirketIdField;
            }
            set {
                if ((this.SirketIdField.Equals(value) != true)) {
                    this.SirketIdField = value;
                    this.RaisePropertyChanged("SirketId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OdemelerWebServis.OdemelerWebServisSoap")]
    public interface OdemelerWebServisSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdemeEkle", ReplyAction="*")]
        RentACarForm.OdemelerWebServis.OdemeEkleResponse OdemeEkle(RentACarForm.OdemelerWebServis.OdemeEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdemeEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.OdemelerWebServis.OdemeEkleResponse> OdemeEkleAsync(RentACarForm.OdemelerWebServis.OdemeEkleRequest request);
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdemelerGuncelle", ReplyAction="*")]
        RentACarForm.OdemelerWebServis.OdemelerGuncelleResponse OdemelerGuncelle(RentACarForm.OdemelerWebServis.OdemelerGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdemelerGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.OdemelerWebServis.OdemelerGuncelleResponse> OdemelerGuncelleAsync(RentACarForm.OdemelerWebServis.OdemelerGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdemelerIdSil", ReplyAction="*")]
        bool OdemelerIdSil(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdemelerIdSil", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> OdemelerIdSilAsync(int id);
        
        // CODEGEN: Generating message contract since element name OdemelerHepsiniSecResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdemelerHepsiniSec", ReplyAction="*")]
        RentACarForm.OdemelerWebServis.OdemelerHepsiniSecResponse OdemelerHepsiniSec(RentACarForm.OdemelerWebServis.OdemelerHepsiniSecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdemelerHepsiniSec", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.OdemelerWebServis.OdemelerHepsiniSecResponse> OdemelerHepsiniSecAsync(RentACarForm.OdemelerWebServis.OdemelerHepsiniSecRequest request);
        
        // CODEGEN: Generating message contract since element name OdemelerIdSecResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdemelerIdSec", ReplyAction="*")]
        RentACarForm.OdemelerWebServis.OdemelerIdSecResponse OdemelerIdSec(RentACarForm.OdemelerWebServis.OdemelerIdSecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdemelerIdSec", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.OdemelerWebServis.OdemelerIdSecResponse> OdemelerIdSecAsync(RentACarForm.OdemelerWebServis.OdemelerIdSecRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OdemeEkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OdemeEkle", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.OdemelerWebServis.OdemeEkleRequestBody Body;
        
        public OdemeEkleRequest() {
        }
        
        public OdemeEkleRequest(RentACarForm.OdemelerWebServis.OdemeEkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OdemeEkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.OdemelerWebServis.Odemeler entity;
        
        public OdemeEkleRequestBody() {
        }
        
        public OdemeEkleRequestBody(RentACarForm.OdemelerWebServis.Odemeler entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OdemeEkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OdemeEkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.OdemelerWebServis.OdemeEkleResponseBody Body;
        
        public OdemeEkleResponse() {
        }
        
        public OdemeEkleResponse(RentACarForm.OdemelerWebServis.OdemeEkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OdemeEkleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool OdemeEkleResult;
        
        public OdemeEkleResponseBody() {
        }
        
        public OdemeEkleResponseBody(bool OdemeEkleResult) {
            this.OdemeEkleResult = OdemeEkleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OdemelerGuncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OdemelerGuncelle", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.OdemelerWebServis.OdemelerGuncelleRequestBody Body;
        
        public OdemelerGuncelleRequest() {
        }
        
        public OdemelerGuncelleRequest(RentACarForm.OdemelerWebServis.OdemelerGuncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OdemelerGuncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.OdemelerWebServis.Odemeler entity;
        
        public OdemelerGuncelleRequestBody() {
        }
        
        public OdemelerGuncelleRequestBody(RentACarForm.OdemelerWebServis.Odemeler entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OdemelerGuncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OdemelerGuncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.OdemelerWebServis.OdemelerGuncelleResponseBody Body;
        
        public OdemelerGuncelleResponse() {
        }
        
        public OdemelerGuncelleResponse(RentACarForm.OdemelerWebServis.OdemelerGuncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OdemelerGuncelleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool OdemelerGuncelleResult;
        
        public OdemelerGuncelleResponseBody() {
        }
        
        public OdemelerGuncelleResponseBody(bool OdemelerGuncelleResult) {
            this.OdemelerGuncelleResult = OdemelerGuncelleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OdemelerHepsiniSecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OdemelerHepsiniSec", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.OdemelerWebServis.OdemelerHepsiniSecRequestBody Body;
        
        public OdemelerHepsiniSecRequest() {
        }
        
        public OdemelerHepsiniSecRequest(RentACarForm.OdemelerWebServis.OdemelerHepsiniSecRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class OdemelerHepsiniSecRequestBody {
        
        public OdemelerHepsiniSecRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OdemelerHepsiniSecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OdemelerHepsiniSecResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.OdemelerWebServis.OdemelerHepsiniSecResponseBody Body;
        
        public OdemelerHepsiniSecResponse() {
        }
        
        public OdemelerHepsiniSecResponse(RentACarForm.OdemelerWebServis.OdemelerHepsiniSecResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OdemelerHepsiniSecResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.OdemelerWebServis.Odemeler[] OdemelerHepsiniSecResult;
        
        public OdemelerHepsiniSecResponseBody() {
        }
        
        public OdemelerHepsiniSecResponseBody(RentACarForm.OdemelerWebServis.Odemeler[] OdemelerHepsiniSecResult) {
            this.OdemelerHepsiniSecResult = OdemelerHepsiniSecResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OdemelerIdSecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OdemelerIdSec", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.OdemelerWebServis.OdemelerIdSecRequestBody Body;
        
        public OdemelerIdSecRequest() {
        }
        
        public OdemelerIdSecRequest(RentACarForm.OdemelerWebServis.OdemelerIdSecRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OdemelerIdSecRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public OdemelerIdSecRequestBody() {
        }
        
        public OdemelerIdSecRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OdemelerIdSecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OdemelerIdSecResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.OdemelerWebServis.OdemelerIdSecResponseBody Body;
        
        public OdemelerIdSecResponse() {
        }
        
        public OdemelerIdSecResponse(RentACarForm.OdemelerWebServis.OdemelerIdSecResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OdemelerIdSecResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.OdemelerWebServis.Odemeler OdemelerIdSecResult;
        
        public OdemelerIdSecResponseBody() {
        }
        
        public OdemelerIdSecResponseBody(RentACarForm.OdemelerWebServis.Odemeler OdemelerIdSecResult) {
            this.OdemelerIdSecResult = OdemelerIdSecResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OdemelerWebServisSoapChannel : RentACarForm.OdemelerWebServis.OdemelerWebServisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OdemelerWebServisSoapClient : System.ServiceModel.ClientBase<RentACarForm.OdemelerWebServis.OdemelerWebServisSoap>, RentACarForm.OdemelerWebServis.OdemelerWebServisSoap {
        
        public OdemelerWebServisSoapClient() {
        }
        
        public OdemelerWebServisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OdemelerWebServisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OdemelerWebServisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OdemelerWebServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.OdemelerWebServis.OdemeEkleResponse RentACarForm.OdemelerWebServis.OdemelerWebServisSoap.OdemeEkle(RentACarForm.OdemelerWebServis.OdemeEkleRequest request) {
            return base.Channel.OdemeEkle(request);
        }
        
        public bool OdemeEkle(RentACarForm.OdemelerWebServis.Odemeler entity) {
            RentACarForm.OdemelerWebServis.OdemeEkleRequest inValue = new RentACarForm.OdemelerWebServis.OdemeEkleRequest();
            inValue.Body = new RentACarForm.OdemelerWebServis.OdemeEkleRequestBody();
            inValue.Body.entity = entity;
            RentACarForm.OdemelerWebServis.OdemeEkleResponse retVal = ((RentACarForm.OdemelerWebServis.OdemelerWebServisSoap)(this)).OdemeEkle(inValue);
            return retVal.Body.OdemeEkleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.OdemelerWebServis.OdemeEkleResponse> RentACarForm.OdemelerWebServis.OdemelerWebServisSoap.OdemeEkleAsync(RentACarForm.OdemelerWebServis.OdemeEkleRequest request) {
            return base.Channel.OdemeEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.OdemelerWebServis.OdemeEkleResponse> OdemeEkleAsync(RentACarForm.OdemelerWebServis.Odemeler entity) {
            RentACarForm.OdemelerWebServis.OdemeEkleRequest inValue = new RentACarForm.OdemelerWebServis.OdemeEkleRequest();
            inValue.Body = new RentACarForm.OdemelerWebServis.OdemeEkleRequestBody();
            inValue.Body.entity = entity;
            return ((RentACarForm.OdemelerWebServis.OdemelerWebServisSoap)(this)).OdemeEkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.OdemelerWebServis.OdemelerGuncelleResponse RentACarForm.OdemelerWebServis.OdemelerWebServisSoap.OdemelerGuncelle(RentACarForm.OdemelerWebServis.OdemelerGuncelleRequest request) {
            return base.Channel.OdemelerGuncelle(request);
        }
        
        public bool OdemelerGuncelle(RentACarForm.OdemelerWebServis.Odemeler entity) {
            RentACarForm.OdemelerWebServis.OdemelerGuncelleRequest inValue = new RentACarForm.OdemelerWebServis.OdemelerGuncelleRequest();
            inValue.Body = new RentACarForm.OdemelerWebServis.OdemelerGuncelleRequestBody();
            inValue.Body.entity = entity;
            RentACarForm.OdemelerWebServis.OdemelerGuncelleResponse retVal = ((RentACarForm.OdemelerWebServis.OdemelerWebServisSoap)(this)).OdemelerGuncelle(inValue);
            return retVal.Body.OdemelerGuncelleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.OdemelerWebServis.OdemelerGuncelleResponse> RentACarForm.OdemelerWebServis.OdemelerWebServisSoap.OdemelerGuncelleAsync(RentACarForm.OdemelerWebServis.OdemelerGuncelleRequest request) {
            return base.Channel.OdemelerGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.OdemelerWebServis.OdemelerGuncelleResponse> OdemelerGuncelleAsync(RentACarForm.OdemelerWebServis.Odemeler entity) {
            RentACarForm.OdemelerWebServis.OdemelerGuncelleRequest inValue = new RentACarForm.OdemelerWebServis.OdemelerGuncelleRequest();
            inValue.Body = new RentACarForm.OdemelerWebServis.OdemelerGuncelleRequestBody();
            inValue.Body.entity = entity;
            return ((RentACarForm.OdemelerWebServis.OdemelerWebServisSoap)(this)).OdemelerGuncelleAsync(inValue);
        }
        
        public bool OdemelerIdSil(int id) {
            return base.Channel.OdemelerIdSil(id);
        }
        
        public System.Threading.Tasks.Task<bool> OdemelerIdSilAsync(int id) {
            return base.Channel.OdemelerIdSilAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.OdemelerWebServis.OdemelerHepsiniSecResponse RentACarForm.OdemelerWebServis.OdemelerWebServisSoap.OdemelerHepsiniSec(RentACarForm.OdemelerWebServis.OdemelerHepsiniSecRequest request) {
            return base.Channel.OdemelerHepsiniSec(request);
        }
        
        public RentACarForm.OdemelerWebServis.Odemeler[] OdemelerHepsiniSec() {
            RentACarForm.OdemelerWebServis.OdemelerHepsiniSecRequest inValue = new RentACarForm.OdemelerWebServis.OdemelerHepsiniSecRequest();
            inValue.Body = new RentACarForm.OdemelerWebServis.OdemelerHepsiniSecRequestBody();
            RentACarForm.OdemelerWebServis.OdemelerHepsiniSecResponse retVal = ((RentACarForm.OdemelerWebServis.OdemelerWebServisSoap)(this)).OdemelerHepsiniSec(inValue);
            return retVal.Body.OdemelerHepsiniSecResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.OdemelerWebServis.OdemelerHepsiniSecResponse> RentACarForm.OdemelerWebServis.OdemelerWebServisSoap.OdemelerHepsiniSecAsync(RentACarForm.OdemelerWebServis.OdemelerHepsiniSecRequest request) {
            return base.Channel.OdemelerHepsiniSecAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.OdemelerWebServis.OdemelerHepsiniSecResponse> OdemelerHepsiniSecAsync() {
            RentACarForm.OdemelerWebServis.OdemelerHepsiniSecRequest inValue = new RentACarForm.OdemelerWebServis.OdemelerHepsiniSecRequest();
            inValue.Body = new RentACarForm.OdemelerWebServis.OdemelerHepsiniSecRequestBody();
            return ((RentACarForm.OdemelerWebServis.OdemelerWebServisSoap)(this)).OdemelerHepsiniSecAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.OdemelerWebServis.OdemelerIdSecResponse RentACarForm.OdemelerWebServis.OdemelerWebServisSoap.OdemelerIdSec(RentACarForm.OdemelerWebServis.OdemelerIdSecRequest request) {
            return base.Channel.OdemelerIdSec(request);
        }
        
        public RentACarForm.OdemelerWebServis.Odemeler OdemelerIdSec(int id) {
            RentACarForm.OdemelerWebServis.OdemelerIdSecRequest inValue = new RentACarForm.OdemelerWebServis.OdemelerIdSecRequest();
            inValue.Body = new RentACarForm.OdemelerWebServis.OdemelerIdSecRequestBody();
            inValue.Body.id = id;
            RentACarForm.OdemelerWebServis.OdemelerIdSecResponse retVal = ((RentACarForm.OdemelerWebServis.OdemelerWebServisSoap)(this)).OdemelerIdSec(inValue);
            return retVal.Body.OdemelerIdSecResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.OdemelerWebServis.OdemelerIdSecResponse> RentACarForm.OdemelerWebServis.OdemelerWebServisSoap.OdemelerIdSecAsync(RentACarForm.OdemelerWebServis.OdemelerIdSecRequest request) {
            return base.Channel.OdemelerIdSecAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.OdemelerWebServis.OdemelerIdSecResponse> OdemelerIdSecAsync(int id) {
            RentACarForm.OdemelerWebServis.OdemelerIdSecRequest inValue = new RentACarForm.OdemelerWebServis.OdemelerIdSecRequest();
            inValue.Body = new RentACarForm.OdemelerWebServis.OdemelerIdSecRequestBody();
            inValue.Body.id = id;
            return ((RentACarForm.OdemelerWebServis.OdemelerWebServisSoap)(this)).OdemelerIdSecAsync(inValue);
        }
    }
}
