//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarForm.MusterilerWebServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Musteriler", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Musteriler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TcKimlikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private System.DateTime DogumTarihiField;
        
        private int MusteriIdField;
        
        private bool KaraListeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentACarForm.MusterilerWebServis.Araclar[] AraclarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciAdiField;
        
        private System.DateTime EhliyetYilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EhliyetTipiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TcKimlik {
            get {
                return this.TcKimlikField;
            }
            set {
                if ((object.ReferenceEquals(this.TcKimlikField, value) != true)) {
                    this.TcKimlikField = value;
                    this.RaisePropertyChanged("TcKimlik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime DogumTarihi {
            get {
                return this.DogumTarihiField;
            }
            set {
                if ((this.DogumTarihiField.Equals(value) != true)) {
                    this.DogumTarihiField = value;
                    this.RaisePropertyChanged("DogumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int MusteriId {
            get {
                return this.MusteriIdField;
            }
            set {
                if ((this.MusteriIdField.Equals(value) != true)) {
                    this.MusteriIdField = value;
                    this.RaisePropertyChanged("MusteriId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool KaraListe {
            get {
                return this.KaraListeField;
            }
            set {
                if ((this.KaraListeField.Equals(value) != true)) {
                    this.KaraListeField = value;
                    this.RaisePropertyChanged("KaraListe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public RentACarForm.MusterilerWebServis.Araclar[] Araclar {
            get {
                return this.AraclarField;
            }
            set {
                if ((object.ReferenceEquals(this.AraclarField, value) != true)) {
                    this.AraclarField = value;
                    this.RaisePropertyChanged("Araclar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string KullaniciAdi {
            get {
                return this.KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciAdiField, value) != true)) {
                    this.KullaniciAdiField = value;
                    this.RaisePropertyChanged("KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.DateTime EhliyetYil {
            get {
                return this.EhliyetYilField;
            }
            set {
                if ((this.EhliyetYilField.Equals(value) != true)) {
                    this.EhliyetYilField = value;
                    this.RaisePropertyChanged("EhliyetYil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string EhliyetTipi {
            get {
                return this.EhliyetTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.EhliyetTipiField, value) != true)) {
                    this.EhliyetTipiField = value;
                    this.RaisePropertyChanged("EhliyetTipi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Araclar", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Araclar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AracIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlakaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracModeliField;
        
        private int GerekenEhliyetYasiField;
        
        private int MinimumYasSiniriField;
        
        private int GunlukKmSiniriField;
        
        private int AracKmField;
        
        private bool HavaYastigiField;
        
        private int BagajHacmiField;
        
        private int KoltukSayisiField;
        
        private int GunlukKiraBedeliField;
        
        private bool RezervField;
        
        private bool KiradaField;
        
        private byte YakitTipiField;
        
        private bool VitesTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracResmiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentACarForm.MusterilerWebServis.Musteriler MusteriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AracId {
            get {
                return this.AracIdField;
            }
            set {
                if ((this.AracIdField.Equals(value) != true)) {
                    this.AracIdField = value;
                    this.RaisePropertyChanged("AracId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Plaka {
            get {
                return this.PlakaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlakaField, value) != true)) {
                    this.PlakaField = value;
                    this.RaisePropertyChanged("Plaka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AracAdi {
            get {
                return this.AracAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AracAdiField, value) != true)) {
                    this.AracAdiField = value;
                    this.RaisePropertyChanged("AracAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AracModeli {
            get {
                return this.AracModeliField;
            }
            set {
                if ((object.ReferenceEquals(this.AracModeliField, value) != true)) {
                    this.AracModeliField = value;
                    this.RaisePropertyChanged("AracModeli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int GerekenEhliyetYasi {
            get {
                return this.GerekenEhliyetYasiField;
            }
            set {
                if ((this.GerekenEhliyetYasiField.Equals(value) != true)) {
                    this.GerekenEhliyetYasiField = value;
                    this.RaisePropertyChanged("GerekenEhliyetYasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int MinimumYasSiniri {
            get {
                return this.MinimumYasSiniriField;
            }
            set {
                if ((this.MinimumYasSiniriField.Equals(value) != true)) {
                    this.MinimumYasSiniriField = value;
                    this.RaisePropertyChanged("MinimumYasSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int GunlukKmSiniri {
            get {
                return this.GunlukKmSiniriField;
            }
            set {
                if ((this.GunlukKmSiniriField.Equals(value) != true)) {
                    this.GunlukKmSiniriField = value;
                    this.RaisePropertyChanged("GunlukKmSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int AracKm {
            get {
                return this.AracKmField;
            }
            set {
                if ((this.AracKmField.Equals(value) != true)) {
                    this.AracKmField = value;
                    this.RaisePropertyChanged("AracKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool HavaYastigi {
            get {
                return this.HavaYastigiField;
            }
            set {
                if ((this.HavaYastigiField.Equals(value) != true)) {
                    this.HavaYastigiField = value;
                    this.RaisePropertyChanged("HavaYastigi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int BagajHacmi {
            get {
                return this.BagajHacmiField;
            }
            set {
                if ((this.BagajHacmiField.Equals(value) != true)) {
                    this.BagajHacmiField = value;
                    this.RaisePropertyChanged("BagajHacmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int KoltukSayisi {
            get {
                return this.KoltukSayisiField;
            }
            set {
                if ((this.KoltukSayisiField.Equals(value) != true)) {
                    this.KoltukSayisiField = value;
                    this.RaisePropertyChanged("KoltukSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int GunlukKiraBedeli {
            get {
                return this.GunlukKiraBedeliField;
            }
            set {
                if ((this.GunlukKiraBedeliField.Equals(value) != true)) {
                    this.GunlukKiraBedeliField = value;
                    this.RaisePropertyChanged("GunlukKiraBedeli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool Rezerv {
            get {
                return this.RezervField;
            }
            set {
                if ((this.RezervField.Equals(value) != true)) {
                    this.RezervField = value;
                    this.RaisePropertyChanged("Rezerv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool Kirada {
            get {
                return this.KiradaField;
            }
            set {
                if ((this.KiradaField.Equals(value) != true)) {
                    this.KiradaField = value;
                    this.RaisePropertyChanged("Kirada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public byte YakitTipi {
            get {
                return this.YakitTipiField;
            }
            set {
                if ((this.YakitTipiField.Equals(value) != true)) {
                    this.YakitTipiField = value;
                    this.RaisePropertyChanged("YakitTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public bool VitesTipi {
            get {
                return this.VitesTipiField;
            }
            set {
                if ((this.VitesTipiField.Equals(value) != true)) {
                    this.VitesTipiField = value;
                    this.RaisePropertyChanged("VitesTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string AracResmi {
            get {
                return this.AracResmiField;
            }
            set {
                if ((object.ReferenceEquals(this.AracResmiField, value) != true)) {
                    this.AracResmiField = value;
                    this.RaisePropertyChanged("AracResmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public RentACarForm.MusterilerWebServis.Musteriler Musteri {
            get {
                return this.MusteriField;
            }
            set {
                if ((object.ReferenceEquals(this.MusteriField, value) != true)) {
                    this.MusteriField = value;
                    this.RaisePropertyChanged("Musteri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MusterilerWebServis.MusterilerWebServisSoap")]
    public interface MusterilerWebServisSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriEkle", ReplyAction="*")]
        RentACarForm.MusterilerWebServis.MusteriEkleResponse MusteriEkle(RentACarForm.MusterilerWebServis.MusteriEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.MusterilerWebServis.MusteriEkleResponse> MusteriEkleAsync(RentACarForm.MusterilerWebServis.MusteriEkleRequest request);
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriGuncelle", ReplyAction="*")]
        RentACarForm.MusterilerWebServis.MusteriGuncelleResponse MusteriGuncelle(RentACarForm.MusterilerWebServis.MusteriGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.MusterilerWebServis.MusteriGuncelleResponse> MusteriGuncelleAsync(RentACarForm.MusterilerWebServis.MusteriGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriIdSil", ReplyAction="*")]
        bool MusteriIdSil(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriIdSil", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> MusteriIdSilAsync(int id);
        
        // CODEGEN: Generating message contract since element name MusteriHepsiniSecResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriHepsiniSec", ReplyAction="*")]
        RentACarForm.MusterilerWebServis.MusteriHepsiniSecResponse MusteriHepsiniSec(RentACarForm.MusterilerWebServis.MusteriHepsiniSecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriHepsiniSec", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.MusterilerWebServis.MusteriHepsiniSecResponse> MusteriHepsiniSecAsync(RentACarForm.MusterilerWebServis.MusteriHepsiniSecRequest request);
        
        // CODEGEN: Generating message contract since element name MusteriIdSecResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriIdSec", ReplyAction="*")]
        RentACarForm.MusterilerWebServis.MusteriIdSecResponse MusteriIdSec(RentACarForm.MusterilerWebServis.MusteriIdSecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriIdSec", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.MusterilerWebServis.MusteriIdSecResponse> MusteriIdSecAsync(RentACarForm.MusterilerWebServis.MusteriIdSecRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriEkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriEkle", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.MusterilerWebServis.MusteriEkleRequestBody Body;
        
        public MusteriEkleRequest() {
        }
        
        public MusteriEkleRequest(RentACarForm.MusterilerWebServis.MusteriEkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MusteriEkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.MusterilerWebServis.Musteriler entity;
        
        public MusteriEkleRequestBody() {
        }
        
        public MusteriEkleRequestBody(RentACarForm.MusterilerWebServis.Musteriler entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriEkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriEkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.MusterilerWebServis.MusteriEkleResponseBody Body;
        
        public MusteriEkleResponse() {
        }
        
        public MusteriEkleResponse(RentACarForm.MusterilerWebServis.MusteriEkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MusteriEkleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool MusteriEkleResult;
        
        public MusteriEkleResponseBody() {
        }
        
        public MusteriEkleResponseBody(bool MusteriEkleResult) {
            this.MusteriEkleResult = MusteriEkleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriGuncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriGuncelle", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.MusterilerWebServis.MusteriGuncelleRequestBody Body;
        
        public MusteriGuncelleRequest() {
        }
        
        public MusteriGuncelleRequest(RentACarForm.MusterilerWebServis.MusteriGuncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MusteriGuncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.MusterilerWebServis.Musteriler entity;
        
        public MusteriGuncelleRequestBody() {
        }
        
        public MusteriGuncelleRequestBody(RentACarForm.MusterilerWebServis.Musteriler entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriGuncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriGuncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.MusterilerWebServis.MusteriGuncelleResponseBody Body;
        
        public MusteriGuncelleResponse() {
        }
        
        public MusteriGuncelleResponse(RentACarForm.MusterilerWebServis.MusteriGuncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MusteriGuncelleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool MusteriGuncelleResult;
        
        public MusteriGuncelleResponseBody() {
        }
        
        public MusteriGuncelleResponseBody(bool MusteriGuncelleResult) {
            this.MusteriGuncelleResult = MusteriGuncelleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriHepsiniSecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriHepsiniSec", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.MusterilerWebServis.MusteriHepsiniSecRequestBody Body;
        
        public MusteriHepsiniSecRequest() {
        }
        
        public MusteriHepsiniSecRequest(RentACarForm.MusterilerWebServis.MusteriHepsiniSecRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MusteriHepsiniSecRequestBody {
        
        public MusteriHepsiniSecRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriHepsiniSecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriHepsiniSecResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.MusterilerWebServis.MusteriHepsiniSecResponseBody Body;
        
        public MusteriHepsiniSecResponse() {
        }
        
        public MusteriHepsiniSecResponse(RentACarForm.MusterilerWebServis.MusteriHepsiniSecResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MusteriHepsiniSecResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.MusterilerWebServis.Musteriler[] MusteriHepsiniSecResult;
        
        public MusteriHepsiniSecResponseBody() {
        }
        
        public MusteriHepsiniSecResponseBody(RentACarForm.MusterilerWebServis.Musteriler[] MusteriHepsiniSecResult) {
            this.MusteriHepsiniSecResult = MusteriHepsiniSecResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriIdSecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriIdSec", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.MusterilerWebServis.MusteriIdSecRequestBody Body;
        
        public MusteriIdSecRequest() {
        }
        
        public MusteriIdSecRequest(RentACarForm.MusterilerWebServis.MusteriIdSecRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MusteriIdSecRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public MusteriIdSecRequestBody() {
        }
        
        public MusteriIdSecRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriIdSecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriIdSecResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.MusterilerWebServis.MusteriIdSecResponseBody Body;
        
        public MusteriIdSecResponse() {
        }
        
        public MusteriIdSecResponse(RentACarForm.MusterilerWebServis.MusteriIdSecResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MusteriIdSecResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.MusterilerWebServis.Musteriler MusteriIdSecResult;
        
        public MusteriIdSecResponseBody() {
        }
        
        public MusteriIdSecResponseBody(RentACarForm.MusterilerWebServis.Musteriler MusteriIdSecResult) {
            this.MusteriIdSecResult = MusteriIdSecResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MusterilerWebServisSoapChannel : RentACarForm.MusterilerWebServis.MusterilerWebServisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MusterilerWebServisSoapClient : System.ServiceModel.ClientBase<RentACarForm.MusterilerWebServis.MusterilerWebServisSoap>, RentACarForm.MusterilerWebServis.MusterilerWebServisSoap {
        
        public MusterilerWebServisSoapClient() {
        }
        
        public MusterilerWebServisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MusterilerWebServisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusterilerWebServisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusterilerWebServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.MusterilerWebServis.MusteriEkleResponse RentACarForm.MusterilerWebServis.MusterilerWebServisSoap.MusteriEkle(RentACarForm.MusterilerWebServis.MusteriEkleRequest request) {
            return base.Channel.MusteriEkle(request);
        }
        
        public bool MusteriEkle(RentACarForm.MusterilerWebServis.Musteriler entity) {
            RentACarForm.MusterilerWebServis.MusteriEkleRequest inValue = new RentACarForm.MusterilerWebServis.MusteriEkleRequest();
            inValue.Body = new RentACarForm.MusterilerWebServis.MusteriEkleRequestBody();
            inValue.Body.entity = entity;
            RentACarForm.MusterilerWebServis.MusteriEkleResponse retVal = ((RentACarForm.MusterilerWebServis.MusterilerWebServisSoap)(this)).MusteriEkle(inValue);
            return retVal.Body.MusteriEkleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.MusterilerWebServis.MusteriEkleResponse> RentACarForm.MusterilerWebServis.MusterilerWebServisSoap.MusteriEkleAsync(RentACarForm.MusterilerWebServis.MusteriEkleRequest request) {
            return base.Channel.MusteriEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.MusterilerWebServis.MusteriEkleResponse> MusteriEkleAsync(RentACarForm.MusterilerWebServis.Musteriler entity) {
            RentACarForm.MusterilerWebServis.MusteriEkleRequest inValue = new RentACarForm.MusterilerWebServis.MusteriEkleRequest();
            inValue.Body = new RentACarForm.MusterilerWebServis.MusteriEkleRequestBody();
            inValue.Body.entity = entity;
            return ((RentACarForm.MusterilerWebServis.MusterilerWebServisSoap)(this)).MusteriEkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.MusterilerWebServis.MusteriGuncelleResponse RentACarForm.MusterilerWebServis.MusterilerWebServisSoap.MusteriGuncelle(RentACarForm.MusterilerWebServis.MusteriGuncelleRequest request) {
            return base.Channel.MusteriGuncelle(request);
        }
        
        public bool MusteriGuncelle(RentACarForm.MusterilerWebServis.Musteriler entity) {
            RentACarForm.MusterilerWebServis.MusteriGuncelleRequest inValue = new RentACarForm.MusterilerWebServis.MusteriGuncelleRequest();
            inValue.Body = new RentACarForm.MusterilerWebServis.MusteriGuncelleRequestBody();
            inValue.Body.entity = entity;
            RentACarForm.MusterilerWebServis.MusteriGuncelleResponse retVal = ((RentACarForm.MusterilerWebServis.MusterilerWebServisSoap)(this)).MusteriGuncelle(inValue);
            return retVal.Body.MusteriGuncelleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.MusterilerWebServis.MusteriGuncelleResponse> RentACarForm.MusterilerWebServis.MusterilerWebServisSoap.MusteriGuncelleAsync(RentACarForm.MusterilerWebServis.MusteriGuncelleRequest request) {
            return base.Channel.MusteriGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.MusterilerWebServis.MusteriGuncelleResponse> MusteriGuncelleAsync(RentACarForm.MusterilerWebServis.Musteriler entity) {
            RentACarForm.MusterilerWebServis.MusteriGuncelleRequest inValue = new RentACarForm.MusterilerWebServis.MusteriGuncelleRequest();
            inValue.Body = new RentACarForm.MusterilerWebServis.MusteriGuncelleRequestBody();
            inValue.Body.entity = entity;
            return ((RentACarForm.MusterilerWebServis.MusterilerWebServisSoap)(this)).MusteriGuncelleAsync(inValue);
        }
        
        public bool MusteriIdSil(int id) {
            return base.Channel.MusteriIdSil(id);
        }
        
        public System.Threading.Tasks.Task<bool> MusteriIdSilAsync(int id) {
            return base.Channel.MusteriIdSilAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.MusterilerWebServis.MusteriHepsiniSecResponse RentACarForm.MusterilerWebServis.MusterilerWebServisSoap.MusteriHepsiniSec(RentACarForm.MusterilerWebServis.MusteriHepsiniSecRequest request) {
            return base.Channel.MusteriHepsiniSec(request);
        }
        
        public RentACarForm.MusterilerWebServis.Musteriler[] MusteriHepsiniSec() {
            RentACarForm.MusterilerWebServis.MusteriHepsiniSecRequest inValue = new RentACarForm.MusterilerWebServis.MusteriHepsiniSecRequest();
            inValue.Body = new RentACarForm.MusterilerWebServis.MusteriHepsiniSecRequestBody();
            RentACarForm.MusterilerWebServis.MusteriHepsiniSecResponse retVal = ((RentACarForm.MusterilerWebServis.MusterilerWebServisSoap)(this)).MusteriHepsiniSec(inValue);
            return retVal.Body.MusteriHepsiniSecResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.MusterilerWebServis.MusteriHepsiniSecResponse> RentACarForm.MusterilerWebServis.MusterilerWebServisSoap.MusteriHepsiniSecAsync(RentACarForm.MusterilerWebServis.MusteriHepsiniSecRequest request) {
            return base.Channel.MusteriHepsiniSecAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.MusterilerWebServis.MusteriHepsiniSecResponse> MusteriHepsiniSecAsync() {
            RentACarForm.MusterilerWebServis.MusteriHepsiniSecRequest inValue = new RentACarForm.MusterilerWebServis.MusteriHepsiniSecRequest();
            inValue.Body = new RentACarForm.MusterilerWebServis.MusteriHepsiniSecRequestBody();
            return ((RentACarForm.MusterilerWebServis.MusterilerWebServisSoap)(this)).MusteriHepsiniSecAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.MusterilerWebServis.MusteriIdSecResponse RentACarForm.MusterilerWebServis.MusterilerWebServisSoap.MusteriIdSec(RentACarForm.MusterilerWebServis.MusteriIdSecRequest request) {
            return base.Channel.MusteriIdSec(request);
        }
        
        public RentACarForm.MusterilerWebServis.Musteriler MusteriIdSec(int id) {
            RentACarForm.MusterilerWebServis.MusteriIdSecRequest inValue = new RentACarForm.MusterilerWebServis.MusteriIdSecRequest();
            inValue.Body = new RentACarForm.MusterilerWebServis.MusteriIdSecRequestBody();
            inValue.Body.id = id;
            RentACarForm.MusterilerWebServis.MusteriIdSecResponse retVal = ((RentACarForm.MusterilerWebServis.MusterilerWebServisSoap)(this)).MusteriIdSec(inValue);
            return retVal.Body.MusteriIdSecResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.MusterilerWebServis.MusteriIdSecResponse> RentACarForm.MusterilerWebServis.MusterilerWebServisSoap.MusteriIdSecAsync(RentACarForm.MusterilerWebServis.MusteriIdSecRequest request) {
            return base.Channel.MusteriIdSecAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.MusterilerWebServis.MusteriIdSecResponse> MusteriIdSecAsync(int id) {
            RentACarForm.MusterilerWebServis.MusteriIdSecRequest inValue = new RentACarForm.MusterilerWebServis.MusteriIdSecRequest();
            inValue.Body = new RentACarForm.MusterilerWebServis.MusteriIdSecRequestBody();
            inValue.Body.id = id;
            return ((RentACarForm.MusterilerWebServis.MusterilerWebServisSoap)(this)).MusteriIdSecAsync(inValue);
        }
    }
}
