//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarForm.SirketWebServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sirket", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Sirket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SirketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SirketAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SehirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        private int AracSayisiField;
        
        private float SirketPuaniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentACarForm.SirketWebServis.Yonetici[] YoneticilerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SirketId {
            get {
                return this.SirketIdField;
            }
            set {
                if ((this.SirketIdField.Equals(value) != true)) {
                    this.SirketIdField = value;
                    this.RaisePropertyChanged("SirketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SirketAdi {
            get {
                return this.SirketAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.SirketAdiField, value) != true)) {
                    this.SirketAdiField = value;
                    this.RaisePropertyChanged("SirketAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Sehir {
            get {
                return this.SehirField;
            }
            set {
                if ((object.ReferenceEquals(this.SehirField, value) != true)) {
                    this.SehirField = value;
                    this.RaisePropertyChanged("Sehir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int AracSayisi {
            get {
                return this.AracSayisiField;
            }
            set {
                if ((this.AracSayisiField.Equals(value) != true)) {
                    this.AracSayisiField = value;
                    this.RaisePropertyChanged("AracSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public float SirketPuani {
            get {
                return this.SirketPuaniField;
            }
            set {
                if ((this.SirketPuaniField.Equals(value) != true)) {
                    this.SirketPuaniField = value;
                    this.RaisePropertyChanged("SirketPuani");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public RentACarForm.SirketWebServis.Yonetici[] Yoneticiler {
            get {
                return this.YoneticilerField;
            }
            set {
                if ((object.ReferenceEquals(this.YoneticilerField, value) != true)) {
                    this.YoneticilerField = value;
                    this.RaisePropertyChanged("Yoneticiler");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Yonetici", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Yonetici : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TcKimlikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private System.DateTime DogumTarihiField;
        
        private int YoneticiIdField;
        
        private int SirketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TcKimlik {
            get {
                return this.TcKimlikField;
            }
            set {
                if ((object.ReferenceEquals(this.TcKimlikField, value) != true)) {
                    this.TcKimlikField = value;
                    this.RaisePropertyChanged("TcKimlik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime DogumTarihi {
            get {
                return this.DogumTarihiField;
            }
            set {
                if ((this.DogumTarihiField.Equals(value) != true)) {
                    this.DogumTarihiField = value;
                    this.RaisePropertyChanged("DogumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int YoneticiId {
            get {
                return this.YoneticiIdField;
            }
            set {
                if ((this.YoneticiIdField.Equals(value) != true)) {
                    this.YoneticiIdField = value;
                    this.RaisePropertyChanged("YoneticiId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int SirketId {
            get {
                return this.SirketIdField;
            }
            set {
                if ((this.SirketIdField.Equals(value) != true)) {
                    this.SirketIdField = value;
                    this.RaisePropertyChanged("SirketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SirketWebServis.SirketWebServisSoap")]
    public interface SirketWebServisSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SirketEkle", ReplyAction="*")]
        RentACarForm.SirketWebServis.SirketEkleResponse SirketEkle(RentACarForm.SirketWebServis.SirketEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SirketEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.SirketWebServis.SirketEkleResponse> SirketEkleAsync(RentACarForm.SirketWebServis.SirketEkleRequest request);
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SirketGuncelle", ReplyAction="*")]
        RentACarForm.SirketWebServis.SirketGuncelleResponse SirketGuncelle(RentACarForm.SirketWebServis.SirketGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SirketGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.SirketWebServis.SirketGuncelleResponse> SirketGuncelleAsync(RentACarForm.SirketWebServis.SirketGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SirketIdSil", ReplyAction="*")]
        bool SirketIdSil(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SirketIdSil", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SirketIdSilAsync(int id);
        
        // CODEGEN: Generating message contract since element name SirketHepsiniSecResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SirketHepsiniSec", ReplyAction="*")]
        RentACarForm.SirketWebServis.SirketHepsiniSecResponse SirketHepsiniSec(RentACarForm.SirketWebServis.SirketHepsiniSecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SirketHepsiniSec", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.SirketWebServis.SirketHepsiniSecResponse> SirketHepsiniSecAsync(RentACarForm.SirketWebServis.SirketHepsiniSecRequest request);
        
        // CODEGEN: Generating message contract since element name SirketIdSecResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SirketIdSec", ReplyAction="*")]
        RentACarForm.SirketWebServis.SirketIdSecResponse SirketIdSec(RentACarForm.SirketWebServis.SirketIdSecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SirketIdSec", ReplyAction="*")]
        System.Threading.Tasks.Task<RentACarForm.SirketWebServis.SirketIdSecResponse> SirketIdSecAsync(RentACarForm.SirketWebServis.SirketIdSecRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SirketEkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SirketEkle", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.SirketWebServis.SirketEkleRequestBody Body;
        
        public SirketEkleRequest() {
        }
        
        public SirketEkleRequest(RentACarForm.SirketWebServis.SirketEkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SirketEkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.SirketWebServis.Sirket entity;
        
        public SirketEkleRequestBody() {
        }
        
        public SirketEkleRequestBody(RentACarForm.SirketWebServis.Sirket entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SirketEkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SirketEkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.SirketWebServis.SirketEkleResponseBody Body;
        
        public SirketEkleResponse() {
        }
        
        public SirketEkleResponse(RentACarForm.SirketWebServis.SirketEkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SirketEkleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SirketEkleResult;
        
        public SirketEkleResponseBody() {
        }
        
        public SirketEkleResponseBody(bool SirketEkleResult) {
            this.SirketEkleResult = SirketEkleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SirketGuncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SirketGuncelle", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.SirketWebServis.SirketGuncelleRequestBody Body;
        
        public SirketGuncelleRequest() {
        }
        
        public SirketGuncelleRequest(RentACarForm.SirketWebServis.SirketGuncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SirketGuncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.SirketWebServis.Sirket entity;
        
        public SirketGuncelleRequestBody() {
        }
        
        public SirketGuncelleRequestBody(RentACarForm.SirketWebServis.Sirket entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SirketGuncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SirketGuncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.SirketWebServis.SirketGuncelleResponseBody Body;
        
        public SirketGuncelleResponse() {
        }
        
        public SirketGuncelleResponse(RentACarForm.SirketWebServis.SirketGuncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SirketGuncelleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SirketGuncelleResult;
        
        public SirketGuncelleResponseBody() {
        }
        
        public SirketGuncelleResponseBody(bool SirketGuncelleResult) {
            this.SirketGuncelleResult = SirketGuncelleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SirketHepsiniSecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SirketHepsiniSec", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.SirketWebServis.SirketHepsiniSecRequestBody Body;
        
        public SirketHepsiniSecRequest() {
        }
        
        public SirketHepsiniSecRequest(RentACarForm.SirketWebServis.SirketHepsiniSecRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SirketHepsiniSecRequestBody {
        
        public SirketHepsiniSecRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SirketHepsiniSecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SirketHepsiniSecResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.SirketWebServis.SirketHepsiniSecResponseBody Body;
        
        public SirketHepsiniSecResponse() {
        }
        
        public SirketHepsiniSecResponse(RentACarForm.SirketWebServis.SirketHepsiniSecResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SirketHepsiniSecResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.SirketWebServis.Sirket[] SirketHepsiniSecResult;
        
        public SirketHepsiniSecResponseBody() {
        }
        
        public SirketHepsiniSecResponseBody(RentACarForm.SirketWebServis.Sirket[] SirketHepsiniSecResult) {
            this.SirketHepsiniSecResult = SirketHepsiniSecResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SirketIdSecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SirketIdSec", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.SirketWebServis.SirketIdSecRequestBody Body;
        
        public SirketIdSecRequest() {
        }
        
        public SirketIdSecRequest(RentACarForm.SirketWebServis.SirketIdSecRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SirketIdSecRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public SirketIdSecRequestBody() {
        }
        
        public SirketIdSecRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SirketIdSecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SirketIdSecResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentACarForm.SirketWebServis.SirketIdSecResponseBody Body;
        
        public SirketIdSecResponse() {
        }
        
        public SirketIdSecResponse(RentACarForm.SirketWebServis.SirketIdSecResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SirketIdSecResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentACarForm.SirketWebServis.Sirket SirketIdSecResult;
        
        public SirketIdSecResponseBody() {
        }
        
        public SirketIdSecResponseBody(RentACarForm.SirketWebServis.Sirket SirketIdSecResult) {
            this.SirketIdSecResult = SirketIdSecResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SirketWebServisSoapChannel : RentACarForm.SirketWebServis.SirketWebServisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SirketWebServisSoapClient : System.ServiceModel.ClientBase<RentACarForm.SirketWebServis.SirketWebServisSoap>, RentACarForm.SirketWebServis.SirketWebServisSoap {
        
        public SirketWebServisSoapClient() {
        }
        
        public SirketWebServisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SirketWebServisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SirketWebServisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SirketWebServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.SirketWebServis.SirketEkleResponse RentACarForm.SirketWebServis.SirketWebServisSoap.SirketEkle(RentACarForm.SirketWebServis.SirketEkleRequest request) {
            return base.Channel.SirketEkle(request);
        }
        
        public bool SirketEkle(RentACarForm.SirketWebServis.Sirket entity) {
            RentACarForm.SirketWebServis.SirketEkleRequest inValue = new RentACarForm.SirketWebServis.SirketEkleRequest();
            inValue.Body = new RentACarForm.SirketWebServis.SirketEkleRequestBody();
            inValue.Body.entity = entity;
            RentACarForm.SirketWebServis.SirketEkleResponse retVal = ((RentACarForm.SirketWebServis.SirketWebServisSoap)(this)).SirketEkle(inValue);
            return retVal.Body.SirketEkleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.SirketWebServis.SirketEkleResponse> RentACarForm.SirketWebServis.SirketWebServisSoap.SirketEkleAsync(RentACarForm.SirketWebServis.SirketEkleRequest request) {
            return base.Channel.SirketEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.SirketWebServis.SirketEkleResponse> SirketEkleAsync(RentACarForm.SirketWebServis.Sirket entity) {
            RentACarForm.SirketWebServis.SirketEkleRequest inValue = new RentACarForm.SirketWebServis.SirketEkleRequest();
            inValue.Body = new RentACarForm.SirketWebServis.SirketEkleRequestBody();
            inValue.Body.entity = entity;
            return ((RentACarForm.SirketWebServis.SirketWebServisSoap)(this)).SirketEkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.SirketWebServis.SirketGuncelleResponse RentACarForm.SirketWebServis.SirketWebServisSoap.SirketGuncelle(RentACarForm.SirketWebServis.SirketGuncelleRequest request) {
            return base.Channel.SirketGuncelle(request);
        }
        
        public bool SirketGuncelle(RentACarForm.SirketWebServis.Sirket entity) {
            RentACarForm.SirketWebServis.SirketGuncelleRequest inValue = new RentACarForm.SirketWebServis.SirketGuncelleRequest();
            inValue.Body = new RentACarForm.SirketWebServis.SirketGuncelleRequestBody();
            inValue.Body.entity = entity;
            RentACarForm.SirketWebServis.SirketGuncelleResponse retVal = ((RentACarForm.SirketWebServis.SirketWebServisSoap)(this)).SirketGuncelle(inValue);
            return retVal.Body.SirketGuncelleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.SirketWebServis.SirketGuncelleResponse> RentACarForm.SirketWebServis.SirketWebServisSoap.SirketGuncelleAsync(RentACarForm.SirketWebServis.SirketGuncelleRequest request) {
            return base.Channel.SirketGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.SirketWebServis.SirketGuncelleResponse> SirketGuncelleAsync(RentACarForm.SirketWebServis.Sirket entity) {
            RentACarForm.SirketWebServis.SirketGuncelleRequest inValue = new RentACarForm.SirketWebServis.SirketGuncelleRequest();
            inValue.Body = new RentACarForm.SirketWebServis.SirketGuncelleRequestBody();
            inValue.Body.entity = entity;
            return ((RentACarForm.SirketWebServis.SirketWebServisSoap)(this)).SirketGuncelleAsync(inValue);
        }
        
        public bool SirketIdSil(int id) {
            return base.Channel.SirketIdSil(id);
        }
        
        public System.Threading.Tasks.Task<bool> SirketIdSilAsync(int id) {
            return base.Channel.SirketIdSilAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.SirketWebServis.SirketHepsiniSecResponse RentACarForm.SirketWebServis.SirketWebServisSoap.SirketHepsiniSec(RentACarForm.SirketWebServis.SirketHepsiniSecRequest request) {
            return base.Channel.SirketHepsiniSec(request);
        }
        
        public RentACarForm.SirketWebServis.Sirket[] SirketHepsiniSec() {
            RentACarForm.SirketWebServis.SirketHepsiniSecRequest inValue = new RentACarForm.SirketWebServis.SirketHepsiniSecRequest();
            inValue.Body = new RentACarForm.SirketWebServis.SirketHepsiniSecRequestBody();
            RentACarForm.SirketWebServis.SirketHepsiniSecResponse retVal = ((RentACarForm.SirketWebServis.SirketWebServisSoap)(this)).SirketHepsiniSec(inValue);
            return retVal.Body.SirketHepsiniSecResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.SirketWebServis.SirketHepsiniSecResponse> RentACarForm.SirketWebServis.SirketWebServisSoap.SirketHepsiniSecAsync(RentACarForm.SirketWebServis.SirketHepsiniSecRequest request) {
            return base.Channel.SirketHepsiniSecAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.SirketWebServis.SirketHepsiniSecResponse> SirketHepsiniSecAsync() {
            RentACarForm.SirketWebServis.SirketHepsiniSecRequest inValue = new RentACarForm.SirketWebServis.SirketHepsiniSecRequest();
            inValue.Body = new RentACarForm.SirketWebServis.SirketHepsiniSecRequestBody();
            return ((RentACarForm.SirketWebServis.SirketWebServisSoap)(this)).SirketHepsiniSecAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentACarForm.SirketWebServis.SirketIdSecResponse RentACarForm.SirketWebServis.SirketWebServisSoap.SirketIdSec(RentACarForm.SirketWebServis.SirketIdSecRequest request) {
            return base.Channel.SirketIdSec(request);
        }
        
        public RentACarForm.SirketWebServis.Sirket SirketIdSec(int id) {
            RentACarForm.SirketWebServis.SirketIdSecRequest inValue = new RentACarForm.SirketWebServis.SirketIdSecRequest();
            inValue.Body = new RentACarForm.SirketWebServis.SirketIdSecRequestBody();
            inValue.Body.id = id;
            RentACarForm.SirketWebServis.SirketIdSecResponse retVal = ((RentACarForm.SirketWebServis.SirketWebServisSoap)(this)).SirketIdSec(inValue);
            return retVal.Body.SirketIdSecResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentACarForm.SirketWebServis.SirketIdSecResponse> RentACarForm.SirketWebServis.SirketWebServisSoap.SirketIdSecAsync(RentACarForm.SirketWebServis.SirketIdSecRequest request) {
            return base.Channel.SirketIdSecAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentACarForm.SirketWebServis.SirketIdSecResponse> SirketIdSecAsync(int id) {
            RentACarForm.SirketWebServis.SirketIdSecRequest inValue = new RentACarForm.SirketWebServis.SirketIdSecRequest();
            inValue.Body = new RentACarForm.SirketWebServis.SirketIdSecRequestBody();
            inValue.Body.id = id;
            return ((RentACarForm.SirketWebServis.SirketWebServisSoap)(this)).SirketIdSecAsync(inValue);
        }
    }
}
